### ISSUE TITLE
Restricting choice to a specific post type

### ISSUE THREAD

**Issue by johannesholmberg** [tmconnect/acf-relationship-multisite#1]
Thanks for an awesome plugin. 

A feature that I’d like to see is a setting for restricting choice to a specific post type.

**Comment by cohpa** [comment]
I'd love to see this feature as well. I haven't tried this plugin yet, but this + the enhancement described above is exactly what I am looking for.

**Comment by tmconnect** [comment]
Unfortunately, this is not possible, which is based on the fact how the CPTs in WordPress are handled.

CPTs are setup in the functions.php or through a plugin. Both actions only fired if the site is loaded and therefore, there is no way in the field settings or in the page editor to access the CPTs of another site.

This is at least my knowledge. If I'm wrong, please let me know.

**Comment by jancbeck** [comment]
To anybody who needs a solution to this issue here is what solved the issue for me:

```php
add_filter('acf/fields/relationship/query', function( $args ){
	$args['post_type'] = 'attorneys';
	return $args;
});
```

This forces the post type for _all_ relationship fields to "attorneys", so you might want to use a field-specific filter:

```php
add_filter('acf/fields/relationship/query/name=' . $field_name, function( $args, $field, $post_id ){ /* ...*/ });
add_filter('acf/fields/relationship/query/key=' . $field_key, function( $args, $field, $post_id ){ /* ...*/ });
```
