### ISSUE TITLE
Uncaught TypeError: Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by jacobdubail** [tmconnect/acf-relationship-multisite#10]
Hi,

I'm running WP 4.2.2, ACF Pro 5.2.7, ACF Relationship Multisite 1.1.0. All other plugins are disabled.

When I scroll through the posts and the ajax request fires to fetch more posts, I get the following error: Uncaught TypeError: Cannot read property 'toLowerCase' of undefined

Here's a 30 second quickcast showing the error: http://quick.as/zgqCqkb2

Are you able to reproduce this?
Thanks,
Jacob

**Comment by manuhook** [comment]
Hi,

I have the same problem here !

**Comment by jacobdubail** [comment]
Hey @tmconnect, any idea what could be the issue here? Thx!

**Comment by tmconnect** [comment]
Should be solved with new version 1.1.01

**Comment by bokkagroup** [comment]
Could you share your fix? We're running into the same issue with our relationship add-on.

Thanks.
