### ISSUE TITLE
Searches cause a JS error

### ISSUE THREAD

**Issue by nabhacosley** [tmconnect/acf-relationship-multisite#11]
Hi there, I've got the multisite field to load fine, but as soon as I try to filter the results, or even just scroll down to see the second page of results, I get an error like this, below.

Any ideas? No AJAX request is being sent when this happens, the error happens first.

<img width="803" alt="screen shot 2015-07-14 at 8 54 58 am" src="https://cloud.githubusercontent.com/assets/2933255/8677909/96cf2030-2a06-11e5-953c-ecab33799788.png">

And here's the field setup:

<img width="760" alt="screen shot 2015-07-14 at 9 02 16 am" src="https://cloud.githubusercontent.com/assets/2933255/8678006/146d34c8-2a07-11e5-88dc-946ae7b209fe.png">

**Comment by tmconnect** [comment]
Should be fixed with new version 1.1.01

**Comment by nabhacosley** [comment]
It works! Thank you very much.
