### ISSUE TITLE
All ACF functions break on page when there's no value

### ISSUE THREAD

**Issue by studiobovenkamer** [tmconnect/acf-relationship-multisite#13]
Hi Thomas,

Thank you for this great add-on! 

I'm experiencing the following problem:

1. when there is a value selected (a custom post type post) from another subsite, everything works as it should.
2. when there is no value selected then every ACF function (that comes after the multisite field) breaks on the page.

`$acf_posts = get_field('trainers'); if( $acf_posts ) : 	... endif;`

A var_dump for get_field('trainers') outputs `string(0) ""`

Using just this piece of code breaks every ACF function on the page when there is no value selected:
`$acf_posts = get_field('trainers');` 

Any idea?

I have the following set up:
- WP 4.2.4
- Using version 'ACF 5.2.7 and newer'. Activated as plug-in but the same problem occurs when included with functions.php. 
- Advanced Custom Field Pro 5.2.9

**Comment by studiobovenkamer** [comment]
**Temporary fix **
I commented line 813 in acf-relationship-multisite-v5.php in the function format_value(). This fixes it for me for now.

**Comment by tmconnect** [comment]
Thanks for your info about this bug. I have changed the acf-relationship-multisite-v5.php (in both versions) so if there's no value selected the script returns to the current blog and you will get all other ACF fields.

**Comment by studiobovenkamer** [comment]
Thanks. Works perfectly!
