### ISSUE TITLE
Choose site when creating post

### ISSUE THREAD

**Issue by jnorton** [tmconnect/acf-relationship-multisite#14]
Love this plugin! Is it possible to use the site select drop-down / search when creating a post? This would enable a post author to select items from various blogs similar to how a multi-site gallery might function. Cheers, J

**Comment by tmconnect** [comment]
I don't quite get it. Can you give me an example what you want to do.

**Comment by tdtm** [comment]
He means being able to select the site to pull posts from at writing time, rather than defining it when creating the post.

**Comment by tmconnect** [comment]
Please take a look at the current ReadMe. Sorry guys...
