### ISSUE TITLE
Does this work as a sub_field

### ISSUE THREAD

**Issue by shivika** [tmconnect/acf-relationship-multisite#15]
I'm trying to pull in a custom post type from the main site to all the subsites using this plugin, but the relationship field is within a repeater and for some reason, it's not showing up at all. Wondering if I'm missing something.  Also, when I try and test the field as a regular field, it only seems to pull in standard posts, not any of the CPTs. Is that intentional?

Thanks!

**Comment by tmconnect** [comment]
I tested this and it works as expected - even in a Cutom Post Type and it fetches CPTs from the other site as well.

![multisite_relationship_in_repareter](https://cloud.githubusercontent.com/assets/2598781/10547524/5d39b898-7435-11e5-8801-8f70e6248b9c.png)

Have you installed the latest versions of ACF and of the plugin? Did you set the field group for the custom post type?

**Comment by shivika** [comment]
I got this working - thank you! But I do have another conundrum:

I have this multisite relationship field as a sub-field in a repeater field on a custom post type page in a subsite.  I am using it to pull cpt posts from the main site and display on the subsite, with some additional acf fields.  The exact scenario is that i have a list of "treatments" (cpt on main site) that I only want the main site to maintain.  Each subsite is a location that needs to be able to add pricing for each treatment.  So on the subsite, I use the multisite relationship field to pull in "treatments" from the main site and then add a price...and this is repeated for multiple treatments.  

My issue is when I go to query and display, I query for my cpt and then try and use the code you've indicated to loop through the repeater and subfields and I am getting nothing. I've played with returning as object and id.  It is strange but when I use return object and  the object example from your site, I get nothing but if i return as object and use the relationship code from the regular acf relationship site (setup post data and use $posts as $post, I get one row of my repeater but that is it.  

I should also note that I set the acf multisite relationship field to select a max of 1 post at a time becuase it will correspond to a price.  Not sure if that makes a difference.

Other thing to note is that I'm sharing this custom field across subsites via the export php code.  

Sorry this is so confusing - I hope it kind of makes sense to you. Here's the code I'm using which may or may not help.  I've been losing my mind trying to get this to work for a day so I figured I'd ask for some help :)

`<?php
  $locquery = new WP_Query( 'post_type=wpsl_stores' );
  if($locquery->have_posts()) : while($locquery->have_posts()) : $locquery->the_post();
  
  $address = get_post_meta( $post->ID, "wpsl_address", true); 
  $address2 = get_post_meta( $post->ID, "wpsl_address2", true); 
  $address2 = get_post_meta( $post->ID, "wpsl_address2", true); 
  $shops = get_post_meta( $post->ID, "wpsl_shopping_center", true); 
  $city = get_post_meta( $post->ID, "wpsl_city", true); 
  $state = get_post_meta( $post->ID, "wpsl_state", true); 
  $zip = get_post_meta( $post->ID, "wpsl_zip", true);
  $phone = get_post_meta( $post->ID, "wpsl_phone", true);
?>   

  <article <?php post_class('location-detail-post'); ?>>
    <header>
      <h1 class="entry-title"><?php echo $city ?>, <?php echo $state ?></h1>
      <h2><?php the_title(); ?></h2>
      <p class="address">
        <span class="address1"><?php echo $address ?></span>
        <?php if ( $address2 )  : ?>
          <span class="address2"><?php echo $address2 ?></span>
        <?php endif; ?>
        <span class="city-state-zip"><?php echo $city ?>, <?php echo $state ?>, <?php echo $zip ?></span>
        <?php if ( $phone )  : ?>
          <span class="phone"><?php echo $phone ?></span>
        <?php endif; ?>
      </p>
    </header>

  <?php endwhile; ?>

    <?php //include( get_template_directory_uri() . '/templates/membership-plans.php'); ?>
    <?php //get_template_part('templates/membership-plans'); ?>
    <div class="entry-content">
     
      <div class="row">
        <div class="col-md-6 rememdy-treatments">
          <table class="table pricing-table">
            <thead>
              <tr>
                <th class="row-1 row-name"><h4>Remedy Treatments</h4></th>
                <th class="row-2 row-member-once">Member<span>once/mo</span></th>
                <th class="row-3 row-member-add">Member<span>addl/mo</span></th>
                <th class="row-4 row-non-member">Regular</th>
              </tr>
            </thead>
            <tbody>
        
        
        <?php
        /*
        * Loop through the repeater field
        */
        if(get_field('treatments_available')): ?>
        
        <?php while(has_sub_field('treatments_available')): ?>
    
          <?php 
          /*
          * Loop through relationship field
          */
          $posts = get_sub_field('treatment_name');

            if( $posts ): 
            switch_to_blog( $posts['site_id'] ); ?>

               <?php foreach( $posts['selected_posts'] as $p):  ?>
                <?php 
                  $regpriceexplode = explode( '.', get_sub_field('treatment_pricing', $p->ID));
                  $regprice = get_sub_field('treatment_pricing', $p->ID);
                  $mempriceraw = $regprice / 2;
                  $memprice = number_format($mempriceraw, 2);
                  $mempriceexplode = explode( '.', $memprice);
                  if( is_object_in_term( $p->ID,'remedy-treatment', 'treatments_cat') ) {
                ?>

                    <tr>
                      <td class="rememdy-item"><?php echo get_the_title( $p->ID ); ?></td>
                      <td>
                        <?php if (get_sub_field('free_for_members', $p->ID) == 'yes') {
                          echo '<em>Free</em>';
                        }
                        else echo '<sup class="dollar-sign">$</sup><span class="dollars">' . $mempriceexplode[0] . '</span><sup class="cents">' . $mempriceexplode[1] . '</sup>';
                        ?>

                      </td>
                      <td><sup class="dollar-sign">$</sup><span class="dollars"><?php echo $mempriceexplode[0] ?></span><sup class="cents"><?php echo $mempriceexplode[1] ?></sup></td>
                      <td><sup class="dollar-sign">$</sup><span class="dollars"><?php echo $regpriceexplode[0] ?></span><sup class="cents"><?php echo $regpriceexplode[1] ?></sup></td>
                    </tr> 
                <?php } ?>
                <?php endforeach; ?>

                 <?php restore_current_blog(); // IMPORTANT switch back to current site?>
            <?php endif; ?>
            <?php endwhile; ?>

          <?php endif; ?>
       <?php wp_reset_postdata(); ?>
    <?php endif; ?>      
    </tbody>
    </table>
  </div>
  
  
  
</div>`

**Comment by tmconnect** [comment]
On my first look, I think that you have to use `get_field()` instead of `get_sub_field()` because as I understand the fields in treatments CPT is not in a repeater.

Hope this helps

    <?php foreach( $posts['selected_posts'] as $p):  ?>
        <?php
        $regpriceexplode = explode( '.', get_field('treatment_pricing', $p->ID));
        $regprice = get_field('treatment_pricing', $p->ID);
        $mempriceraw = $regprice / 2;
        $memprice = number_format($mempriceraw, 2);
        $mempriceexplode = explode( '.', $memprice);
        if ( is_object_in_term( $p->ID,'remedy-treatment', 'treatments_cat') ) { ?>
            <tr>
                <td class="rememdy-item"><?php echo get_the_title( $p->ID ); ?></td>
                <td>
                    <?php if (get_field('free_for_members', $p->ID) == 'yes') {
                        echo '<em>Free</em>';
                    } else {
                        echo '<sup class="dollar-sign">$</sup><span class="dollars">' . $mempriceexplode[0] . '</span><sup class="cents">' . $mempriceexplode[1] . '</sup>';
                    } ?>
                </td>
                <td><sup class="dollar-sign">$</sup><span class="dollars"><?php echo $mempriceexplode[0] ?></span><sup class="cents"><?php echo $mempriceexplode[1] ?></sup></td>
                <td><sup class="dollar-sign">$</sup><span class="dollars"><?php echo $regpriceexplode[0] ?></span><sup class="cents"><?php echo $regpriceexplode[1] ?></sup></td>
            </tr> 
        <?php } ?>
    <?php endforeach; ?>

**Comment by tmconnect** [comment]
Please take a look at the current ReadMe. Sorry guys...
