### ISSUE TITLE
No results in backend

### ISSUE THREAD

**Issue by joemaci** [tmconnect/acf-relationship-multisite#16]
Hello! Thanks for your job, im very interested in that plugin. But i have a problem, no posts display in the backend when i want to select. Only shows the box (You are looking on posts from site....) and the dropbox, but nothing more. I have ACF v 5.3.2. What do you think is the problem? What can i do to fix it?
Thank you ver much!

**Comment by Nicholas-Cardot** [comment]
I'm having this same issue and checking the console produces the following error:

Failed to load resource: the server responded with a status of 500 (Internal Server Error): http://domain.com/wp-content/plugins/home/minygear/public_html/wp-content/themes/theme_name/acf-multisite/js/input.js?ver=4.4.1

**Comment by olivierhaustrate** [comment]
same kind of issue...
the custom posts types I want the user to be able to select from are not even listed. the WP pages and posts are listed, but not the custom posts types. I have ACF v 5.3.1 installed

thanks in advance

**Comment by tmconnect** [comment]
Please take a look at the current ReadMe. Sorry guys...
