### ISSUE TITLE
Allow the user to select the site to choose from?

### ISSUE THREAD

**Issue by BoweFrankema** [tmconnect/acf-relationship-multisite#17]
Awesome work on this extension for ACF! I was wondering if there is a way to let a user choose the subsite to select from? Currently you (the developer) selects the subsite but it would be awesome if this could be done by the user itself. Maybe this is technically impossible or outside of the scope of this plugin but I thought I'd ask anyway :-)

**Comment by alanpilloud** [comment]
:+1:

I would need that too.

**Comment by tmconnect** [comment]
Please take a look at the current ReadMe. Sorry guys...
