### ISSUE TITLE
Force post type

### ISSUE THREAD

**Issue by alanpilloud** [tmconnect/acf-relationship-multisite#18]
Hello,

First of all, thanks for your great plugin !

I'd like to know if there is any way to force a post type and don't let the user choose between all available post types ?

Have a nice day

**Comment by olivierhaustrate** [comment]
same question...

I would like to add a field box to let the user choose some posts from a specific custom post type from a specific blog.

so far the posts for the custom post type I want to offer the user to select from are not even listed...

Thanks in advance

**Comment by tmconnect** [comment]
Please take a look at the current ReadMe. Sorry guys...
