### ISSUE TITLE
Split into two separate repositories

### ISSUE THREAD

**Issue by persand** [tmconnect/acf-relationship-multisite#19]
Thanks for a great plugin!

Could you split up the code of the two different plugins into two repositories? If so it would be possible to install them with Composer.

**Comment by persand** [comment]
I made a temporary fork of 5.2.7 and newer here:

https://github.com/kollegorna/acf-relationship-multisite

**Comment by tmconnect** [comment]
Please take a look at the current ReadMe. Sorry guys...
