### ISSUE TITLE
Post type filter list is from current blog

### ISSUE THREAD

**Issue by Jeroendebeurs** [tmconnect/acf-relationship-multisite#21]
Hi,

First of all great addon! I would like to use it but have an issue. 
When you want to filter on the post type (in editor mode) you get a list of post types from the current blog. The post types of the other site on the multisite are different. So I wouldn't be able to use this post type filter.

I see you use acf_get_post_types(); on line 458 of acf-relationship-multisite-v5.php. I tried to switch (switch_to_blog( $field['site'] );) to the other site there, this doesn't work unfortunately. Do you have a solution?

Thanks!
Jeroen
![non-matching-filter](https://cloud.githubusercontent.com/assets/7581556/15679571/a7c1919e-2752-11e6-8f7d-e3cee5b5639f.jpg)

**Comment by hellosubscription** [comment]
yes, just doesn't work. it also doesn't show the custom post types in the left column of the target site.

**Comment by davemac** [comment]
I have the same issue, too. Using WordPress 4.5.3.

**Comment by tmconnect** [comment]
Please take a look at the current ReadMe. Sorry guys...
