### ISSUE TITLE
Possible to make this addon workable on single blog dev enviroment?

### ISSUE THREAD

**Issue by bastian-w** [tmconnect/acf-relationship-multisite#3]
Hi,

is it possible to make this plugin work on a single non multisite installation? I'm developing my templates and ACF's on a non multisite, but it will be used on a multisite later. But if i use that plugin my whole ACF crashes. Is ist possible to make it work even on a single site installation without crashing my whole acf? I would change the acf_get_sites() function. The wp_get_sites() throws an undefined function error. So maybe its possible to get a fallback into that function? It's my first multisite project so maybe i can't see the related problems which would cause that change.

**Comment by tmconnect** [comment]
Please take a look at the current ReadMe. Sorry guys...
