### ISSUE TITLE
The module doesn't "switch back" to the current blog

### ISSUE THREAD

**Issue by alkah3st** [tmconnect/acf-relationship-multisite#8]
When I use this module in a page template in a context like this:

```
get_header();
the_post();

// first, get universal staff members
$universal_staff = get_field("staff_members_outside");
			
// have to call this because of the multisite field leaving it hanging...
restore_current_blog();
```

I have to switch back to the current blog, otherwise everything that follows the field call remains switched to the blog from which I retrieved the posts via the field.

**Comment by tmconnect** [comment]
Can't reconstruct this issue and it can not really be, because the `get_field('fieldname')` does not switch the the site. It's only getting the field value as an array.

You can check it this way
```
echo "Before get_field() function the current site is " . $current_blog->domain . "<br/>";
$universal_staff = get_field("staff_members_outside");
echo "After get_field() function the current site is " . $current_blog->domain . "<br/>";
```

Maybe you have an earlier call of switch_to_blog() in your page template.

**Comment by alkah3st** [comment]
I'll give that test a try and get back to you, thanks!
