### ISSUE TITLE
Compatibility with ACF Pro 5.2.7

### ISSUE THREAD

**Issue by pranksinatra** [tmconnect/acf-relationship-multisite#9]
First of all, thanks for an awesome plugin.

Yesterday I upgraded ACF Pro to version 5.2.7 and got the following error:

`Fatal error: Call to undefined function acf_force_type_array() in /var/www/gc_responsive/wp-content/plugins/acf-relationship-multisite-master/acf-relationship-multisite-v5.php on line 444`

Evidently, this function doesn't exist in 5.2.7. In 5.2.6 it's located on line 1195 in api-helpers.php.

**Comment by tmconnect** [comment]
Thanks for this - it's resolved with new version
